### ISSUE TITLE
Migrate from npm to pnpm for improved performance 

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-react-app-playground#105]
## Description:
Migrate from using npm to pnpm for improved performance / space efficiency

## Tasks:

- [ ] Install pnpm globally
```
npm install -g pnpm
```

- [ ] Convert package-lock.json and  generate pnpm-lock.yaml file
```
pnpm import
pnpm install
```

- [ ] Add a node script to prevent npm  (https://pnpm.io/only-allow-pnpm)

```
 "scripts": {
		"preinstall": "npx only-allow pnpm"
	}
```
- [ ] Convert npm scripts in package.json to pnpm equivalents / replace any npm-specific commands 
- [ ] Update .gitignore 
   ```
   pnpm-lock.yaml
   .pnpm-store/
   ```

- [ ] Update CI/CD pipelines to use pnpm if neccesary

## Acceptance Criteria:

* All npm commands are replaced with pnpm equivalents
* CI/CD pipelines successfully run with pnpm
* All tests pass 

Resources:
https://pnpm.io/
