### ISSUE TITLE
Story: Update app module architecture with NCIDS components

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-react-app-playground#97]
## As a developer, I want to update the architecture of the app module, so that I can implement NCIDS components.

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: User can see NCIDS components on application home page
  Given the application has implemented NCIDS components
  When a user views the home page of the application
  Then the user sees the NCIDS Banner component
    And the user sees the NCIDS Header component
    And the user sees the NCIDS Sidenav component
    And the user sees the NCIDS Footer component
```

### Resources:
* Web Page: [*Here goes a URL to an existing web page*](https://www.cancer.gov/)

### Notes
With the creation of NCIDS, we are planning to update the app modules with the new NCIDS components. We will need to refactor the architecture of our app modules to support these new components.

---

### Tasks
- [x] Get NCIDS into build (webpack)
- [x] Update react-app-dev preview page (index.html)
  - Remove common.css and use a new common css file that is like ncids-minimal.scss (similar to CGDP)
  - Needs to include usa-banner, nci-header, usa-footer
  - Nice to have: include side nav on app modules that display it (this is not part of ncids-minimal.scss)
- [ ] Create ncids-application-page.scss
- [ ] Update app module to use NCIDS

### Technical Notes
- `cgdp-application-page-title`
